### ISSUE TITLE
Mod no longer working in newest version of Among Us

### ISSUE THREAD

**Issue by SubSmallWorldGames** [CrowdedMods/CustomServersClient#13]
Among Us update seems to have broken the mod!

**Comment by roobscoob** [comment]
(v2020.12.3)

**Comment by przebor** [comment]
Created pull request with working version for newest Steam release. 
#15

**Comment by przebor** [comment]
Ok, so Among Us has just got a next new update. I'm working on rewriting class definitions yet again, I will probably make a PR for that tomorrow.

**Comment by przebor** [comment]
Created yet another #16 to support newest version from Steam.

**Comment by przebor** [comment]
Outdated. I suggest closing.
Latest version of CSC supports 2020.12.9s, but seems like the release is broken.

**Comment by przebor** [comment]
Now it works ig.
