### ISSUE TITLE
[Feature] Support ports other than 22023

### ISSUE THREAD

**Issue by Sanae6** [CrowdedMods/CustomServersClient#14]
Among Us hard-codes the port to 22023 even if you change it in a RegionInfo entry. If you look in a dnSpy decompile, you can see that's the case, and find out where it gets hardcoded. 

<details>
<summary>this was written before 12.3 got released :)</summary>
I'm looking into it, but not sure on the mappings at this point, if i find the correct information I'll send it here
</details>

**Comment by przebor** [comment]
Tested, works fine for me. If you still encounter this issue, please reopen.
