### ISSUE TITLE
Does the CustomServersClient work with 2020.12.9s?

### ISSUE THREAD

**Issue by Psych0-Smil3s** [CrowdedMods/CustomServersClient#18]
I can not get it to work in the newest version. Either i am doing something wrong or the mod has been patched. Any info on this?

**Comment by MatadorProBr** [comment]
The mod still works well, I see some problems when putting it with the other mod but I managed to solve it, if you are trying to do this, delete the BelpnEx folder, download the BelpnEx they sent and the files too, put everything in the Among Us, open Among Us and it should be working

**Comment by vmas123** [comment]
I'm having trouble getting this to work. In the bottom right of have that manager servers button but no idea how to add servers to it

**Comment by przebor** [comment]
Now it does ig
