### ISSUE TITLE
Error in among us console thingy

### ISSUE THREAD

**Issue by char-mines** [CrowdedMods/CustomServersClient#2]
Hello I have this error:
Could not load type IPCOMKKGKCK, Assembly-CSharp, Version=3.7.1.6, Culture=neutral, PublicKeyToken=null while decoding custom attribute: (null)
Please help!

**Comment by char-mines** [comment]
It says wrong version of BepInEx but isnt there only the 0.0.0 version???

**Comment by char-mines** [comment]
Got the version thing to go away but still have the original error

**Comment by IAmTheAg** [comment]
You're running the wrong version of Among Us. You'll get this error if you try to run this plugin on a version that is too old or too new. From what I can tell, 1.1 ONLY works on 10.22, and 1.0 ONLY works on 9.22

**Comment by silvervirus** [comment]
any plans to support 2020.11.4s

**Comment by DispatchCommit** [comment]
I tried on both 2020.10.22s and 2020.11.4s and I don't see any UI elements. No errors show up for 10.22, but it doesn't seem to be active

**Comment by silvervirus** [comment]
> 
> 
> I tried on both 2020.10.22s and 2020.11.4s and I don't see any UI elements. No errors show up for 10.22, but it doesn't seem to be active

i got some errors on 2020.11.4s because they changed the name of the location of the options are linked to . also you need to install BepInEx that he tell you to install

**Comment by przebor** [comment]
Outdated. I suggest closing.
Latest version of CSC supports 2020.12.9s, but seems like the release is broken.
