### ISSUE TITLE
Could not load type RegionMenu

### ISSUE THREAD

**Issue by KintonHiryuu** [CrowdedMods/CustomServersClient#23]
Hi, here's my problem :
fresh Amongus Install (works fine)
Installed CustomServersClient using the links in the tutorial (readme.md)
Started the game, clicks to select a server, i got the fade, but not the servers list

here's my BepInEx logs : 
[LogOutput.log](https://github.com/CrowdedMods/CustomServersClient/files/6291620/LogOutput.log)

System Infos : WS10 home 2004 (US-us), installed using steam

**Comment by Galster-dev** [comment]
What Among Us version do you use?

**Comment by KintonHiryuu** [comment]
last one - 2021.3.31.3s

**Comment by Galster-dev** [comment]
Then you have to compile branch `airship` yourself and replace its dll in `BepInEx/plugins`
@przebor merge and release when?

**Comment by przebor** [comment]
I was waiting for 6pak to organize all things but it seems like he won't do that soon. I will release in a moment.

**Comment by KintonHiryuu** [comment]
oh ok mybad, must have tought earlier since it's the same with impostor
