### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by amitco140** [CrowdedMods/CustomServersClient#4]
after im done adding regions, how can I remove the MANAGER REGIONS button and the console that opening in the start before among us launch

**Comment by XtraCube** [comment]
To remove the console, go into your Among us folder, then navigate to `Bepinex/Config` and open BepInEx.cfg in a text editor. Search for Logging.Console and change the `Enabled` value to `false`. To remove the MANAGE REGIONS button, clone the repo and edit the code yourself

**Comment by przebor** [comment]
Outdated and irrelevant. I suggest closing.

**Comment by amitco140** [comment]
Closed.
