### ISSUE TITLE
Doesn't work with the newest version of 11.17

### ISSUE THREAD

**Issue by XtraCube** [CrowdedMods/CustomServersClient#8]
Trying to use the Client with the latest version of 11.17 gives you an error when trying to open the game. Making a pull request to fix it

**Comment by andruzzzhka** [comment]
Are you **absolutely sure** that you are using the latest version of Among Us?
You can check this by looking in the `assembly-hash.txt` file in the `Among Us\BepInEx\unhollowed` folder
The hash for the latest version is `463585f0d1a4071ae006ce8b515d8888`

**Comment by XtraCube** [comment]
I'm sure I'm using the latest version since I updated it, but the assembly hash says `694eb5fc543c951ebe5767ad148bd16a`

**Comment by andruzzzhka** [comment]
Hash `694eb5fc543c951ebe5767ad148bd16a` corresponds to [this manifest](https://steamdb.info/depot/945361/history/?changeid=M:982761632128031721), which is **not** the latest. So this just confirms that you don't have the latest version of the game.
The latest manifest right now is [this one](https://steamdb.info/depot/945361/history/?changeid=M:2101726827626605419), and the mod is targetting it.
Unfortunately, both of these manifests have the same version number (v2020.11.17) in the game, so they are not easy to distinguish.
